"""
Pydantic models used across the API for request/response validation
and for the internal shape of analysis results.
"""
from __future__ import annotations

from typing import List, Optional
from pydantic import BaseModel, Field


class UploadResponse(BaseModel):
    file_id: str
    filename: str
    file_type: str
    characters_extracted: int
    preview: str
    message: str = "File processed successfully."


class JobDescriptionRequest(BaseModel):
    text: Optional[str] = None
    file_id: Optional[str] = None


class AnalyzeRequest(BaseModel):
    resume_file_id: str
    jd_file_id: Optional[str] = None
    jd_text: Optional[str] = None


class SkillCoverage(BaseModel):
    matched_skills: List[str]
    missing_skills: List[str]
    resume_skill_count: int
    jd_skill_count: int
    coverage_percent: float


class ATSBreakdownItem(BaseModel):
    category: str
    score: float
    max_score: float
    explanation: str


class ATSResult(BaseModel):
    total_score: float
    max_score: float = 100.0
    breakdown: List[ATSBreakdownItem]
    disclaimer: str = (
        "This is an educational, ATS-style estimate generated by a rule-based "
        "and NLP heuristic model. It does not reflect the scoring logic of any "
        "specific commercial Applicant Tracking System."
    )


class SuggestionItem(BaseModel):
    category: str
    severity: str  # "high" | "medium" | "low"
    suggestion: str


class ChartSeries(BaseModel):
    labels: List[str]
    values: List[float]


class ChartsData(BaseModel):
    skill_match_pie: ChartSeries
    ats_radar: ChartSeries
    skill_distribution_bar: ChartSeries


class AnalysisResult(BaseModel):
    analysis_id: str
    resume_match_score: float
    ats_score: ATSResult
    skills: SkillCoverage
    suggestions: List[SuggestionItem]
    charts: ChartsData
    analyzed_at: str
